- name: Deploy Java Application to Tomcat
  hosts: ec2_instances
  become: yes
  tasks:
    - name: Download student.war
      get_url:
        url: https://tomcat.apache.org/tomcat-7.0-doc/appdev/sample/sample.war
        dest: "/tmp/student.war"  # Temporary location to download the file

    - name: Move WAR file to Tomcat webapps directory
      copy:
        src: "/tmp/student.war"
        dest: "/opt/apache-tomcat-9.0.50/webapps/"
