- name: Deploy Java Application to Tomcat
  hosts: ec2_instances
  become: yes
  tasks:
    - name: Copy WAR file to Tomcat webapps directory
      copy:
        src: /path/to/your/app.war
        dest: /opt/apache-tomcat-9.0.50/webapps/
